apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ds-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kapil4457/Expense-Tracker---Configuration.git"
    targetRevision: main
    path: argocd-k8s-manifests/ds-service
  destination:
    server: https://kubernetes.default.svc
    namespace: expense-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
