apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userservice;
    CREATE DATABASE IF NOT EXISTS authservice;
    CREATE DATABASE IF NOT EXISTS expenseservice;
