apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-service
  template:
    metadata:
      labels:
        app: kong-service
    spec:
      containers:
        - name: kong
          image: kapil4457/expense-tracker-kong-service:latest
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8443
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/usr/local/kong/declarative/kong.yaml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: KONG_LOG_LEVEL
              value: "debug"
            - name: KONG_PLUGINS
              value: "custom-auth"
            - name: KONG_LUA_PACKAGE_PATH
              value: "/usr/local/share/lua/5.1/?.lua;;"
          volumeMounts:
            - name: kong-config
              mountPath: /usr/local/kong/declarative/kong.yaml
              subPath: kong.yaml
            - name: kong-plugins
              mountPath: /usr/local/share/lua/5.1/kong/plugins/custom-auth
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
        - name: kong-plugins
          configMap:
            name: kong-plugins
