apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;",
            ]
        - name: wait-for-kafka
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;",
            ]
      containers:
        - name: auth-service
          image: kapil4457/expense-tracker-auth-service:0f8a5363c3d5e70bc7a23a57912c6c46159de7bd
          ports:
            - containerPort: 9898
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: "authservice"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: KAFKA_HOST
              value: "kafka"
            - name: KAFKA_PORT
              value: "9092"
